"""Enforce unique constraint on user reviews

Revision ID: 5ab9c8ff7815
Revises: 8927867c3a9e
Create Date: 2025-03-02 17:09:12.345320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab9c8ff7815'
down_revision: Union[str, None] = '8927867c3a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_book_review_uc', 'reviews', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_book_review_uc', 'reviews', type_='unique')
    # ### end Alembic commands ###
